---  
- hosts: localhost
  become: true
  gather_facts: yes
  collections: 
  - ch_collections.base
  roles:
    - { role: /root/roles/nfs_mounts }
    - name: ch_collections.base.cloudwatch_agent_config
      when: cw_log_files is defined
