Vagrant.configure("2") do |config|
  config.vm.box = "gbailey/amzn2"
  config.vm.define "docker-vm"
  config.vm.network "forwarded_port", guest: 21000, host: 21000
  config.vm.network "forwarded_port", guest: 21001, host: 21001
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbook.yml"
  end
end
