---  
- hosts: docker-vm
  become: true
  gather_facts: yes
  roles:
    - docker
    - lifecycle-scripts
    - name: ch_collections.heritage_services.nfs
      vars:
        install_watcher_service: false
  tasks: 
    - name: Copy deployment playbooks to server for runtime setup
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/root/{{ item | basename }}"
        mode: 0755
      loop:
        - deployment.yml
