---  
- hosts: docker-vm
  become: true
  gather_facts: yes
  roles:
    - docker
    - lifecycle-scripts
    - ch_collections.base.nagios_nrpe_client
    - name: ch_collections.heritage_services.nfs
      vars:
        install_watcher_service: false
    - sshfs
  tasks: 
    - name: Setup deployment playbook dependancies (1/2)  
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/root/{{ item | basename }}"
        mode: 0755
      loop: 
        - deployment.yml
        - requirements.yml

    - name: Setup deployment playbook dependancies (2/2)
      ansible.builtin.command: 
        cmd: "/usr/local/bin/ansible-galaxy install -f -r /root/requirements.yml"
      register: requirements_output
      changed_when: '"was installed successfully" in requirements_output.stdout'
